directory:
  submit: ./Submit
  output: ./Output
  done: ./Done
  error: ./ERROR
  src_path: ./src
  pot_path_GGA: /data/vasp4us/pot/PBE52
  pot_path_LDA: /data/vasp4us/pot/LDA52

program:
  vasp_std: /data/vasp4us/vasp_std
  vasp_gam: /data/vasp4us/vasp_gam
  vasp_ncl: /data/vasp4us/vasp_ncl
  gnuplot: /gnuplot

calculation:
  kp_test: 1
  encut_test: 0
  relaxation: 0
  band: 0
  density_of_states: 0
  hse_oneshot: 0
  dielectric: 0
  effective_mass: 0
  plot: 1
  magnetic_ordering: 0
  large_off: -1

cif2vasp:
  POT_name:
    GGA:
#      Ge: Ge
    LDA: 
#      Ge: Ge
  SOC_target:
#    - Bi
#    - Tl
#    - Pb
  U_value:
#    La: 7.5
#    Ce: 4.5
  magmom: 3
  max_nelm: 100
  INCAR:

vasp_parallel:
  npar: 2
  kpar: 2

converge_test:
  ENCONV: 0.01
  PRCONV: 10
  FOCONV: -1
  initial_kpl: 1
  max_kpl: 20
  ENSTART: 200
  ENSTEP: 50
  ENMAX: 1000

relaxation:
  potential_type:
    - GGA
#    - LDA
  max_iteration: 10
  converged_ionic_step: 5
  pos_warning_percent: 1
  INCAR:
#    EDIFF: 1e-08

band_calculation:
  kspacing_for_band: 0.01
  type_of_kpt: all              # band (only for band structure plot)
  y_min: 3                      # set plot region, downward from VBM
  y_max: 2                      # set plot region, upward from CBM
  potential_type:
    - GGA
#    - LDA
  relax_check: 1
  INCAR:

Hybrid_oneshot:
  alpha: 0.25
  INCAR:

density_of_states:
  potential_type:
    - GGA
#    - LDA
  relax_check: 1
  KP_multiplier: 2
  y_min: 3                      # set plot region, downward from VBM
  y_max: 2                      # set plot region, upward from CBM
  INCAR:

dielectric:
  KP_multiplier: 2
  potential_type:
    - GGA
#    - LDA
  INCAR:
    EDIFF: 1e-08
#    EDIFFG: 1e-04
  metal_check: 1
  relax_check: 1

effective_mass:
  carrier_type:
    - hole
    - electron
  pocket_search_dist: 0.1
  grid_size_for_searching: 0.02
  grid_size_for_calculation: 0.02
  temperature_for_Fermi: 300
  Fermi_for_cutoff: 0.9
  potential_type:
    - GGA
#    - LDA
  INCAR:

magnetic_ordering:
  from_relax: 0
  cutoff_for_parameter: 5.0
  Tolerance: 0.01
  Genetic_algorithm:
    min_iteration: 0
    max_iteration: -1
    selection_coeff: 2
    population:
      best: 15
      crossover: 30
      mutation: 30
      random: 15
